apiVersion: apps/v1
Kind: Pod
metaData: 
  name: ticket-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: client
  template:
    metadata: 
      label:
        app: client
    spec:
      containers:
        - name: client
          image: ms/client
