apiVersion: apps/v1
Kind: Pod
metaData: 
  name: ticket-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: comment
  template:
    metadata: 
      label:
        app: comment
    spec:
      containers:
        - name: comment
          image: ms/comment
