apiVersion: apps/v1
Kind: Pod
metaData: 
  name: ticket-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: eventBus
  template:
    metadata: 
      label:
        app: eventBus
    spec:
      containers:
        - name: eventBus
          image: ms/eventBus
